#!/bin/bash
# MOAB/Torque submission script for SciNet GPC (OpenMP)
#
#PBS -l nodes=1:ppn=8,walltime=10:00:00
#PBS -N run

cd $PBS_O_WORKDIR

# load modules (must match modules used for compilation)
module load intel/16.0.3
export OMP_STACKSIZE=2000M
export OMP_NUM_THREADS=8
# DIRECTORY TO RUN - $PBS_O_WORKDIR is directory job was submitted from

#export OMP_NUM_THREADS=8
./run
